### PR TITLE
Add Fast Marching method

### LINKED ISSUE #42: [BUG] "Fast marching" implementation doe not use Eikonal update formula
**Describe the bug**
Having looked through the code, it seems that the implementation of `geodis_fastmarch.cpp` does not use any Eikonal update formula:
https://github.com/masadcv/FastGeodis/blob/7101eb32a0541e0d5657c1cf7aba92811a640c57/FastGeodis/geodis_fastmarch.cpp#L120-L138
As such, it probably isn't really implementing fast marching.

**To Reproduce**
Look at the output of the current fastmarching for Euclidean distance:
https://github.com/masadcv/FastGeodis/blob/7101eb32a0541e0d5657c1cf7aba92811a640c57/samples/simpledemo2d.py#L106
Star artefacts are as pronounced as those in Toivanen approach. See also #40 

**Expected behavior**
A much better approximation of the distance map should be achievable through fast marching.

**Additional context**
A good description of fast marching can be found in the following technical report:
Bærentzen, J. A. (2001). On the implementation of fast marching methods for 3D lattices.
http://www2.imm.dtu.dk/pubdb/pubs/841-full.html

A python wrapper for a basic c++ implementation of fast marching can be found in the [scikit-fmm](https://github.com/scikit-fmm/scikit-fmm) package.

A standalone c++, header-only implementation of fast marcing can be found here:
https://github.com/tvercaut/fast-marching-method
It would make sense to replace teh current implementation in the FastGeodis repo by that provided in fast-marching-method.

### PR DESCRIPTION
**Pull request by masadcv**
Fixes #42 and issues raised in #40

This PR implements Fast Marching Method as indicated in #42 

It has the following changes:
- [x] Existing Fast Marching was the pixel queue methods from  Ikonen, L., & Toivanen, P. (2007). Distance and nearest neighbor transforms on gray-level surfaces. Pattern Recognition Letters, 28(5), 604-612. and hence it has been renamed to `pixelqueue` method
- [x] Included Fast Marching method (FMM) based on https://github.com/tvercaut/fast-marching-method
- [x] Implement gradient based speed for FMM for geodesic distance using example from #42 
- [x] Update unittests
- [x] Update docs
- [x] Update examples
- [x] Update README

### CODE REVIEW

**Comment by tvercaut** [comment]
For clarity, it may be good to clean up a bit the pixel queue implementation. Maybe adding some comments to refer back to the algorithm described in
https://doi.org/10.1016/j.patrec.2006.10.010

Also, I would replace the hand-crafted heaps by a standard use of a `std::priority_queue`:
https://en.cppreference.com/w/cpp/container/priority_queue

For the fast marching, could you fetch the [fast-marching-method](https://github.com/tvercaut/fast-marching-method) repo or add it as a git submodule rather than copying the file here?

**Comment by masadcv** [comment]
Many thanks! 
For pixel queue related work, I have added an issue for general code cleanup and improvements as your proposed (issue #46 ) as I would like to keep this PR for adding complete FMM functionality and renaming existing method to pixel queue. 

I will look into FMM submodule bit, I would ideally like to keep installations hassle-free (e.g. pip install git+repo or pip install FastGeodis), which is one of the reason why I copied the file over. I will try submodules, if not then copy the working directory of FMM git as dependency like done in SimpleCRF [here](https://github.com/HiLab-git/SimpleCRF/tree/master/dependency)

**Comment by masadcv** [comment]
It would be good if you could verify FMM methods' output  (if your schedule permits). 

Here is a quick overview of what I am getting:
For 2d:

fig2d


For 3d:

fig3d

**Comment by masadcv** [comment]
@tvercaut
I have been testing the fmm method in this branch. 
It seems like there are certain scenarios where this fails with error:
`RuntimeError: invalid arrival time (distance) -nan at index [xxx, xxx]`

This happens especially for signed distance calculation when image is bigger and only a single seed point is selected. 
Here is a failing example using the scaled image (if you set scale to 1, everything works as expected):
https://colab.research.google.com/drive/1BXbJcoEf9Ib9aXIsWjcMwNWlV5HRgBaq?usp=sharing 

I am unsure what is causing this, do you know?

**Comment by tvercaut** [comment]
Fast marching uses the inverse of the speed and even the inverse of the square of the speed. The most likely explanation is that your speed contains too low values.

Looking at
https://github.com/masadcv/FastGeodis/blob/100a4e4dc363d063b08b5680b28a3cd1d0db67b1/FastGeodis/geodis_fastmarch.cpp#L183
I would be more conservative. At least use sqrt(machine_espilon) rather than machine_espilon.

There might be other issues but I'll start with this.

Also, unrelated to numerical stability but you should use the high-accuracy eikonal solver here:
https://github.com/masadcv/FastGeodis/blob/100a4e4dc363d063b08b5680b28a3cd1d0db67b1/FastGeodis/geodis_fastmarch.cpp#L47-L51

**Comment by masadcv** [comment]
> I added a fallback in case the Eikonal equation is degenerate in this branch: https://github.com/tvercaut/fast-marching-method/tree/negativediscriminant
> 
> Can you give it a try?

Many thanks! Let me give it a try now.

**Comment by masadcv** [comment]
I have included both sqrt(eps) and degenerate fallback within this PR. It is stable now and works fine for all cases. 
I will go ahead and merge this after some local testing. 
If any further issues then please raise a bug and I can look into it. 

Thanks once again for your help with FMM, it wouldn't have been possible without it.

**Comment by tvercaut** [comment]
Nice. Thanks!

**Pull request merged**
